### ISSUE TITLE
Update documentation URLs for v3.2.0 release

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox-plugin-tutorial#1]
The guide intentionally links to the documentation for NetBox's `feature` branch. This will need to be updated to `stable` once v3.2.0 is released.

**Comment by emersonfelipesp** [comment]
I have just add the base documentation and external links to the **[Netbox Plugins Store](https://github.com/emersonfelipesp/netbox-plugins-store)**, I hope it can be useful.
