### ISSUE TITLE
Feature Suggestion: NetBox 3.2 Support

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-plugin-tutorial#12]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released

**Comment by DanSheps** [comment]
Issueception here @ryanmerolle?

**Comment by ryanmerolle** [comment]
haha got overzealous going through the list of plugins spreading the news
